language: node_js

node_js:
  - "8"
  - "6"

after_success: "npm run coveralls"

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: npm
  email: zoltan.lajos.kis@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

